// AUTO-GENERATED by scripts/sync-reports.mjs — do not edit.
import type { ScheduleMeta, WatchlistMeta } from "./manifest-types";

export const SCHEDULE_IDS: string[] = ["001-watchlist-1"];

export const SCHEDULES: ScheduleMeta[] = [
  {
    "id": "001-watchlist-1",
    "schedule_id": 1,
    "name": "watchlist-1",
    "persona": "swing",
    "watchlist_id": 2,
    "watchlist_name": "test",
    "updated_at": "2026-07-11T02:36:05.617752+00:00",
    "version_count": 7,
    "latest_version": "20260711T023605Z",
    "latest_generated_at": "2026-07-11T02:36:05.617752+00:00",
    "latest_candidate_count": 9,
    "ai_versions": [
      "20260710T042523Z",
      "20260711T023605Z"
    ]
  }
];

export const WATCHLISTS: WatchlistMeta[] = [
  {
    "watchlist_id": 2,
    "name": "test",
    "slug": "2",
    "schedules": [
      "001-watchlist-1"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-11T02:36:05.617752+00:00",
    "report_count": 7,
    "latest": {
      "scheduleId": "001-watchlist-1",
      "version": "20260711T023605Z",
      "generated_at": "2026-07-11T02:36:05.617752+00:00",
      "persona": "swing",
      "candidate_count": 9,
      "hasAi": true
    }
  }
];
