// AUTO-GENERATED by scripts/sync-reports.mjs — do not edit.
import type { ScheduleMeta, WatchlistMeta } from "./manifest-types";

export const SCHEDULE_IDS: string[] = ["008-information-technology","009-financials","010-energy","011-industrials","012-utilities","013-health-care"];

export const SCHEDULES: ScheduleMeta[] = [
  {
    "id": "008-information-technology",
    "schedule_id": 8,
    "name": "Information Technology",
    "persona": "swing",
    "watchlist_id": 4,
    "watchlist_name": "Information technology",
    "updated_at": "2026-07-22T12:16:07.823750+00:00",
    "version_count": 8,
    "latest_version": "20260722T121607Z",
    "latest_generated_at": "2026-07-22T12:16:07.823750+00:00",
    "latest_candidate_count": 41,
    "ai_versions": [],
    "diff_versions": [
      "20260722T121607Z",
      "20260722T001609Z",
      "20260721T221618Z",
      "20260721T121611Z",
      "20260721T001609Z",
      "20260720T221635Z",
      "20260720T121604Z",
      "20260719T224217Z"
    ],
    "outcome_versions": [
      "20260721T001609Z",
      "20260720T221635Z",
      "20260720T121604Z",
      "20260719T224217Z"
    ]
  },
  {
    "id": "009-financials",
    "schedule_id": 9,
    "name": "Financials",
    "persona": "swing",
    "watchlist_id": 5,
    "watchlist_name": "Financials",
    "updated_at": "2026-07-22T12:17:43.454857+00:00",
    "version_count": 8,
    "latest_version": "20260722T121743Z",
    "latest_generated_at": "2026-07-22T12:17:43.454857+00:00",
    "latest_candidate_count": 33,
    "ai_versions": [],
    "diff_versions": [
      "20260722T121743Z",
      "20260722T001745Z",
      "20260721T221751Z",
      "20260721T121744Z",
      "20260721T001744Z",
      "20260720T221826Z",
      "20260720T121754Z",
      "20260719T224450Z"
    ],
    "outcome_versions": [
      "20260721T001744Z",
      "20260720T221826Z"
    ]
  },
  {
    "id": "010-energy",
    "schedule_id": 10,
    "name": "Energy",
    "persona": "swing",
    "watchlist_id": 9,
    "watchlist_name": "Energy",
    "updated_at": "2026-07-22T12:19:19.443889+00:00",
    "version_count": 8,
    "latest_version": "20260722T121919Z",
    "latest_generated_at": "2026-07-22T12:19:19.443889+00:00",
    "latest_candidate_count": 12,
    "ai_versions": [
      "20260720T121920Z"
    ],
    "diff_versions": [
      "20260722T121919Z",
      "20260722T001920Z",
      "20260721T221927Z",
      "20260721T121920Z",
      "20260721T001921Z",
      "20260720T221931Z",
      "20260720T121920Z",
      "20260719T224532Z"
    ],
    "outcome_versions": []
  },
  {
    "id": "011-industrials",
    "schedule_id": 11,
    "name": "Industrials",
    "persona": "swing",
    "watchlist_id": 7,
    "watchlist_name": "Industrials",
    "updated_at": "2026-07-22T12:21:50.701914+00:00",
    "version_count": 8,
    "latest_version": "20260722T122150Z",
    "latest_generated_at": "2026-07-22T12:21:50.701914+00:00",
    "latest_candidate_count": 40,
    "ai_versions": [],
    "diff_versions": [
      "20260722T122150Z",
      "20260722T002153Z",
      "20260721T222159Z",
      "20260721T122147Z",
      "20260721T002148Z",
      "20260720T222215Z",
      "20260720T122200Z",
      "20260719T224702Z"
    ],
    "outcome_versions": [
      "20260721T002148Z",
      "20260720T222215Z",
      "20260720T122200Z",
      "20260719T224702Z"
    ]
  },
  {
    "id": "012-utilities",
    "schedule_id": 12,
    "name": "Utilities",
    "persona": "swing",
    "watchlist_id": 8,
    "watchlist_name": "Utilities",
    "updated_at": "2026-07-22T12:23:32.592505+00:00",
    "version_count": 8,
    "latest_version": "20260722T122332Z",
    "latest_generated_at": "2026-07-22T12:23:32.592505+00:00",
    "latest_candidate_count": 24,
    "ai_versions": [],
    "diff_versions": [
      "20260722T122332Z",
      "20260722T002335Z",
      "20260721T222341Z",
      "20260721T122328Z",
      "20260721T002328Z",
      "20260720T222343Z",
      "20260720T122334Z",
      "20260719T224840Z"
    ],
    "outcome_versions": [
      "20260720T122334Z",
      "20260719T224840Z"
    ]
  },
  {
    "id": "013-health-care",
    "schedule_id": 13,
    "name": "Health Care",
    "persona": "swing",
    "watchlist_id": 6,
    "watchlist_name": "Health Care",
    "updated_at": "2026-07-22T12:25:45.232737+00:00",
    "version_count": 8,
    "latest_version": "20260722T122545Z",
    "latest_generated_at": "2026-07-22T12:25:45.232737+00:00",
    "latest_candidate_count": 35,
    "ai_versions": [],
    "diff_versions": [
      "20260722T122545Z",
      "20260722T002548Z",
      "20260721T222556Z",
      "20260721T122543Z",
      "20260721T002545Z",
      "20260720T222600Z",
      "20260720T122552Z",
      "20260719T224937Z"
    ],
    "outcome_versions": [
      "20260720T122552Z",
      "20260719T224937Z"
    ]
  }
];

export const WATCHLISTS: WatchlistMeta[] = [
  {
    "watchlist_id": 4,
    "name": "Information technology",
    "slug": "4",
    "schedules": [
      "008-information-technology"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-22T12:16:07.823750+00:00",
    "report_count": 8,
    "latest": {
      "scheduleId": "008-information-technology",
      "version": "20260722T121607Z",
      "generated_at": "2026-07-22T12:16:07.823750+00:00",
      "persona": "swing",
      "candidate_count": 41,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 5,
    "name": "Financials",
    "slug": "5",
    "schedules": [
      "009-financials"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-22T12:17:43.454857+00:00",
    "report_count": 8,
    "latest": {
      "scheduleId": "009-financials",
      "version": "20260722T121743Z",
      "generated_at": "2026-07-22T12:17:43.454857+00:00",
      "persona": "swing",
      "candidate_count": 33,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 6,
    "name": "Health Care",
    "slug": "6",
    "schedules": [
      "013-health-care"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-22T12:25:45.232737+00:00",
    "report_count": 8,
    "latest": {
      "scheduleId": "013-health-care",
      "version": "20260722T122545Z",
      "generated_at": "2026-07-22T12:25:45.232737+00:00",
      "persona": "swing",
      "candidate_count": 35,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 7,
    "name": "Industrials",
    "slug": "7",
    "schedules": [
      "011-industrials"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-22T12:21:50.701914+00:00",
    "report_count": 8,
    "latest": {
      "scheduleId": "011-industrials",
      "version": "20260722T122150Z",
      "generated_at": "2026-07-22T12:21:50.701914+00:00",
      "persona": "swing",
      "candidate_count": 40,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 8,
    "name": "Utilities",
    "slug": "8",
    "schedules": [
      "012-utilities"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-22T12:23:32.592505+00:00",
    "report_count": 8,
    "latest": {
      "scheduleId": "012-utilities",
      "version": "20260722T122332Z",
      "generated_at": "2026-07-22T12:23:32.592505+00:00",
      "persona": "swing",
      "candidate_count": 24,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 9,
    "name": "Energy",
    "slug": "9",
    "schedules": [
      "010-energy"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-22T12:19:19.443889+00:00",
    "report_count": 8,
    "latest": {
      "scheduleId": "010-energy",
      "version": "20260722T121919Z",
      "generated_at": "2026-07-22T12:19:19.443889+00:00",
      "persona": "swing",
      "candidate_count": 12,
      "hasAi": false
    }
  }
];
