// AUTO-GENERATED by scripts/sync-reports.mjs — do not edit.
import type { ScheduleMeta, WatchlistMeta } from "./manifest-types";

export const SCHEDULE_IDS: string[] = ["002-information-technology","003-financials","004-energy","005-industrials","006-utilities","007-health-care"];

export const SCHEDULES: ScheduleMeta[] = [
  {
    "id": "002-information-technology",
    "schedule_id": 2,
    "name": "Information Technology",
    "persona": "swing",
    "watchlist_id": 4,
    "watchlist_name": "Information technology",
    "updated_at": "2026-07-14T19:35:57.218710+00:00",
    "version_count": 12,
    "latest_version": "20260714T193557Z",
    "latest_generated_at": "2026-07-14T19:35:57.218710+00:00",
    "latest_candidate_count": 41,
    "ai_versions": []
  },
  {
    "id": "003-financials",
    "schedule_id": 3,
    "name": "Financials",
    "persona": "swing",
    "watchlist_id": 5,
    "watchlist_name": "Financials",
    "updated_at": "2026-07-14T19:35:44.863785+00:00",
    "version_count": 11,
    "latest_version": "20260714T193544Z",
    "latest_generated_at": "2026-07-14T19:35:44.863785+00:00",
    "latest_candidate_count": 32,
    "ai_versions": []
  },
  {
    "id": "004-energy",
    "schedule_id": 4,
    "name": "Energy",
    "persona": "swing",
    "watchlist_id": 9,
    "watchlist_name": "Energy",
    "updated_at": "2026-07-14T19:34:44.254605+00:00",
    "version_count": 11,
    "latest_version": "20260714T193444Z",
    "latest_generated_at": "2026-07-14T19:34:44.254605+00:00",
    "latest_candidate_count": 13,
    "ai_versions": []
  },
  {
    "id": "005-industrials",
    "schedule_id": 5,
    "name": "Industrials",
    "persona": "swing",
    "watchlist_id": 7,
    "watchlist_name": "Industrials",
    "updated_at": "2026-07-14T19:35:46.512106+00:00",
    "version_count": 11,
    "latest_version": "20260714T193546Z",
    "latest_generated_at": "2026-07-14T19:35:46.512106+00:00",
    "latest_candidate_count": 31,
    "ai_versions": []
  },
  {
    "id": "006-utilities",
    "schedule_id": 6,
    "name": "Utilities",
    "persona": "swing",
    "watchlist_id": 8,
    "watchlist_name": "Utilities",
    "updated_at": "2026-07-14T19:35:13.749001+00:00",
    "version_count": 11,
    "latest_version": "20260714T193513Z",
    "latest_generated_at": "2026-07-14T19:35:13.749001+00:00",
    "latest_candidate_count": 19,
    "ai_versions": []
  },
  {
    "id": "007-health-care",
    "schedule_id": 7,
    "name": "Health Care",
    "persona": "swing",
    "watchlist_id": 6,
    "watchlist_name": "Health Care",
    "updated_at": "2026-07-14T19:35:41.878112+00:00",
    "version_count": 11,
    "latest_version": "20260714T193541Z",
    "latest_generated_at": "2026-07-14T19:35:41.878112+00:00",
    "latest_candidate_count": 30,
    "ai_versions": []
  }
];

export const WATCHLISTS: WatchlistMeta[] = [
  {
    "watchlist_id": 4,
    "name": "Information technology",
    "slug": "4",
    "schedules": [
      "002-information-technology"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-14T19:35:57.218710+00:00",
    "report_count": 12,
    "latest": {
      "scheduleId": "002-information-technology",
      "version": "20260714T193557Z",
      "generated_at": "2026-07-14T19:35:57.218710+00:00",
      "persona": "swing",
      "candidate_count": 41,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 5,
    "name": "Financials",
    "slug": "5",
    "schedules": [
      "003-financials"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-14T19:35:44.863785+00:00",
    "report_count": 11,
    "latest": {
      "scheduleId": "003-financials",
      "version": "20260714T193544Z",
      "generated_at": "2026-07-14T19:35:44.863785+00:00",
      "persona": "swing",
      "candidate_count": 32,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 6,
    "name": "Health Care",
    "slug": "6",
    "schedules": [
      "007-health-care"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-14T19:35:41.878112+00:00",
    "report_count": 11,
    "latest": {
      "scheduleId": "007-health-care",
      "version": "20260714T193541Z",
      "generated_at": "2026-07-14T19:35:41.878112+00:00",
      "persona": "swing",
      "candidate_count": 30,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 7,
    "name": "Industrials",
    "slug": "7",
    "schedules": [
      "005-industrials"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-14T19:35:46.512106+00:00",
    "report_count": 11,
    "latest": {
      "scheduleId": "005-industrials",
      "version": "20260714T193546Z",
      "generated_at": "2026-07-14T19:35:46.512106+00:00",
      "persona": "swing",
      "candidate_count": 31,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 8,
    "name": "Utilities",
    "slug": "8",
    "schedules": [
      "006-utilities"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-14T19:35:13.749001+00:00",
    "report_count": 11,
    "latest": {
      "scheduleId": "006-utilities",
      "version": "20260714T193513Z",
      "generated_at": "2026-07-14T19:35:13.749001+00:00",
      "persona": "swing",
      "candidate_count": 19,
      "hasAi": false
    }
  },
  {
    "watchlist_id": 9,
    "name": "Energy",
    "slug": "9",
    "schedules": [
      "004-energy"
    ],
    "personas": [
      "swing"
    ],
    "updated_at": "2026-07-14T19:34:44.254605+00:00",
    "report_count": 11,
    "latest": {
      "scheduleId": "004-energy",
      "version": "20260714T193444Z",
      "generated_at": "2026-07-14T19:34:44.254605+00:00",
      "persona": "swing",
      "candidate_count": 13,
      "hasAi": false
    }
  }
];
