/**
 * Mirror committed report data (data/reports/**) into public/reports/** so it is
 * served as static assets on Cloudflare (free tier, no R2/KV needed for report blobs).
 * Runs automatically via the `predev` / `prebuild` npm scripts.
 *
 * Also emits src/lib/reports-manifest.ts: the schedule id list PLUS a watchlist-keyed grouping
 * (WATCHLISTS) so the dashboard can be organized by watchlist (universe.watchlist_id) rather than by
 * the scheduler that produced the reports. All fs reads here happen at build; the Worker has no fs.
 */
import { cp, rm, mkdir, stat, readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "data", "reports");
const dest = join(root, "public", "reports");
const manifest = join(root, "src", "lib", "reports-manifest.ts");

async function readJsonSafe(path) {
	try {
		return JSON.parse(await readFile(path, "utf-8"));
	} catch {
		return null;
	}
}

/** Build a ScheduleMeta for one schedule folder (reads its index.json + latest run for the watchlist id). */
async function scheduleMeta(scheduleId, files) {
	const dir = join(src, scheduleId);
	const index = await readJsonSafe(join(dir, "index.json"));
	// The watchlist identity lives in the run's `universe`, not in index.json — read the latest run.
	const latestRun = (await readJsonSafe(join(dir, "latest.json"))) ?? {};
	const universe = latestRun.universe ?? {};
	const versions = index?.versions ?? [];
	const latest = versions[0] ?? null;
	const aiVersions = files
		.filter((f) => f.endsWith(".ai.json"))
		.map((f) => f.slice(0, -".ai.json".length));
	return {
		id: scheduleId,
		schedule_id: index?.schedule_id ?? 0,
		name: index?.name ?? scheduleId,
		persona: index?.persona ?? latestRun.persona ?? "swing",
		watchlist_id: universe.watchlist_id ?? index?.schedule_id ?? 0,
		watchlist_name: universe.name ?? index?.name ?? scheduleId,
		updated_at: index?.updated_at ?? "",
		version_count: versions.length,
		latest_version: latest?.version ?? null,
		latest_generated_at: latest?.generated_at ?? null,
		latest_candidate_count: latest?.candidate_count ?? 0,
		ai_versions: aiVersions,
	};
}

/** Invert schedules → watchlists (group by watchlist_id; pick the newest run across schedules as `latest`). */
function groupWatchlists(schedules) {
	const byId = new Map();
	for (const s of schedules) {
		const key = s.watchlist_id;
		if (!byId.has(key)) {
			byId.set(key, {
				watchlist_id: s.watchlist_id,
				name: s.watchlist_name,
				slug: String(s.watchlist_id),
				schedules: [],
				personas: [],
				updated_at: "",
				report_count: 0,
				latest: null,
			});
		}
		const w = byId.get(key);
		w.schedules.push(s.id);
		w.report_count += s.version_count;
		if (s.persona && !w.personas.includes(s.persona)) w.personas.push(s.persona);
		if (s.updated_at > w.updated_at) w.updated_at = s.updated_at;
		const cand = s.latest_version
			? {
					scheduleId: s.id,
					version: s.latest_version,
					generated_at: s.latest_generated_at ?? "",
					persona: s.persona,
					candidate_count: s.latest_candidate_count,
					hasAi: s.ai_versions.includes(s.latest_version),
			  }
			: null;
		if (cand && (!w.latest || cand.generated_at > w.latest.generated_at)) w.latest = cand;
	}
	return [...byId.values()].sort((a, b) => a.watchlist_id - b.watchlist_id);
}

async function main() {
	try {
		await stat(src);
	} catch {
		console.warn(`[sync-reports] no source at ${src} — skipping`);
		return;
	}
	await rm(dest, { recursive: true, force: true });
	await mkdir(dest, { recursive: true });
	await cp(src, dest, { recursive: true });
	console.log(`[sync-reports] copied ${src} -> ${dest}`);

	const entries = await readdir(src, { withFileTypes: true });
	const ids = entries.filter((e) => e.isDirectory()).map((e) => e.name).sort();

	const schedules = [];
	for (const id of ids) {
		const files = await readdir(join(src, id));
		schedules.push(await scheduleMeta(id, files));
	}
	const watchlists = groupWatchlists(schedules);

	const body =
		`// AUTO-GENERATED by scripts/sync-reports.mjs — do not edit.\n` +
		`import type { ScheduleMeta, WatchlistMeta } from "./manifest-types";\n\n` +
		`export const SCHEDULE_IDS: string[] = ${JSON.stringify(ids)};\n\n` +
		`export const SCHEDULES: ScheduleMeta[] = ${JSON.stringify(schedules, null, 2)};\n\n` +
		`export const WATCHLISTS: WatchlistMeta[] = ${JSON.stringify(watchlists, null, 2)};\n`;
	await writeFile(manifest, body);
	console.log(
		`[sync-reports] wrote manifest (${ids.length} schedules, ${watchlists.length} watchlists) -> ${manifest}`,
	);
}

main().catch((err) => {
	console.error("[sync-reports] failed:", err);
	process.exit(1);
});
