/**
 * Mirror committed report data (data/reports/**) into public/reports/** so it is
 * served as static assets on Cloudflare (free tier, no R2/KV needed for report blobs).
 * Runs automatically via the `predev` / `prebuild` npm scripts.
 */
import { cp, rm, mkdir, stat, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "data", "reports");
const dest = join(root, "public", "reports");
const manifest = join(root, "src", "lib", "reports-manifest.ts");

async function main() {
	try {
		await stat(src);
	} catch {
		console.warn(`[sync-reports] no source at ${src} — skipping`);
		return;
	}
	await rm(dest, { recursive: true, force: true });
	await mkdir(dest, { recursive: true });
	await cp(src, dest, { recursive: true });
	console.log(`[sync-reports] copied ${src} -> ${dest}`);

	// Bundle the schedule id list so runtime code (e.g. the /app redirect) never reads the filesystem
	// — the Cloudflare Worker has no fs. fs reads for report *contents* still happen at build only.
	const ids = (await readdir(src, { withFileTypes: true }))
		.filter((e) => e.isDirectory())
		.map((e) => e.name)
		.sort();
	const body =
		`// AUTO-GENERATED by scripts/sync-reports.mjs — do not edit.\n` +
		`export const SCHEDULE_IDS: string[] = ${JSON.stringify(ids)};\n`;
	await writeFile(manifest, body);
	console.log(`[sync-reports] wrote manifest (${ids.length} schedules) -> ${manifest}`);
}

main().catch((err) => {
	console.error("[sync-reports] failed:", err);
	process.exit(1);
});
